name: test

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  clojure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeLaGuardo/setup-clojure@13.4
        with:
          cli: latest
      - run: clojure -M:test
